project_name: red-cli

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go generate ../../...

release:
  prerelease: auto
  name_template: "v{{.Version}}"
  draft: false
  mode: "keep-existing"

builds:
  - main: ./cmd/red
    binary: red-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64

universal_binaries:
  - name_template: red-cli
    replace: true

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - README.md
      - LICENSE

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'

#publishers:
#  - name: Ubuntu, Debian APT
#    cmd: ./script/apt.sh {{ .Version }}

scoop:
  bucket:
    owner: mrjefflarry
    name: redmine-cli
  homepage: "https://github.com/mrjefflarry/redmine-cli"
  description: "Redmine CLI"

nfpms:
  - vendor: mrjefflarry
    homepage: https://github.com/mrjefflarry/redmine-cli
    maintainer: Jeff Hägerman
    description: |-
      Drum rolls installer package.
      Software to create fast and easy drum rolls.

    # Formats to be generated.
    formats:
      - deb

    recommends:
      - less
      - nano

snapcrafts:
  - summary: Redmine CLI
    name: red-cli
    publish: false
    description: Redmine CLI for interacting with Redmine Servers
    grade: stable
    confinement: strict
    apps:
      red-cli:
        plugs: [ "home", "network" ]

brews:
  - tap:
      owner: mrjefflarry
      name: redmine-cli
    homepage: https://github.com/mrjefflarry/redmine-cli
    description: "Redmine CLI"
    install: |-
      bin.install "red-cli"
    test: |
      system "#{bin}/red-cli -v"