project_name: red-cli

before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go generate ../../...

release:
  prerelease: auto
  name_template: "v{{.Version}}"
  draft: false
  mode: "keep-existing"

builds:
  - main: ./cmd/red
    binary: red-cli
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
    goarm:
      - 6
      - 7
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64

universal_binaries:
  - name_template: red-cli
    replace: true

archives:
  - files:
      - README.md
      - LICENSE

changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^build:'

scoops:
  - repository:
      owner: mrjefflarry
      name: redmine-cli
    homepage: "https://github.com/mrjefflarry/redmine-cli"
    description: "Redmine CLI"

nfpms:
  - vendor: mrjefflarry
    homepage: https://github.com/mrjefflarry/redmine-cli
    maintainer: Jeff Hägerman
    description: Redmine CLI for interacting with Redmine Servers

    # Formats to be generated.
    formats:
      - deb

    recommends:
      - less
      - nano

# sandbox with snap does not work well when open nano or less from red-cli
# drop support as of now, use apt instead
# could use confinement as "classic" then it should work, need to apply for it at snap forum
#snapcrafts:
#  - summary: Redmine CLI
#    name: red-cli
#    publish: false
#    description: Redmine CLI for interacting with Redmine Servers
#    grade: stable
#    confinement: strict
#    apps:
#      red-cli:
#        plugs: [ "home", "network" ]

brews:
  - repository:
      owner: mrjefflarry
      name: redmine-cli
    homepage: https://github.com/mrjefflarry/redmine-cli
    description: "Redmine CLI"
    install: |-
      bin.install "red-cli"
    test: |
      system "#{bin}/red-cli -v"