# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedCli < Formula
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.0.8"

  on_macos do
    url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.8/red-cli_0.0.8_Darwin_all.tar.gz"
    sha256 "f43c761839b35b03aba3b6be2f2ee16e8255127ca67331e6be8a62e9b8f0703f"

    def install
      bin.install "red-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.8/red-cli_0.0.8_Linux_x86_64.tar.gz"
      sha256 "acb2f2f08a181e2412217110001cc331bb4887574b6530b4f3ab5565bfbd9c2b"

      def install
        bin.install "red-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.8/red-cli_0.0.8_Linux_arm64.tar.gz"
      sha256 "ee408b7480027e7ecc84c00e9c1a6903a47e8a64bfa2ec7ca7b88a1c5b269237"

      def install
        bin.install "red-cli"
      end
    end
  end

  test do
    system "#{bin}/red-cli -v"
  end
end
