# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RedCli < Formula
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.0.8"

  on_macos do
    url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.8/red-cli_0.0.8_Darwin_all.tar.gz"
    sha256 "2a73d2a8dc153c8dc9784fc40273bf5665ac1b8d1c7bbbc4d79e98030e8db7b6"

    def install
      bin.install "red-cli"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.8/red-cli_0.0.8_Linux_x86_64.tar.gz"
      sha256 "2d305a58e85fe77d4355f63fd1bb74bc9e5a198bdbd05612deaccf2923761367"

      def install
        bin.install "red-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.8/red-cli_0.0.8_Linux_arm64.tar.gz"
      sha256 "93cc625ef5fa41a3af838a12fc9c8fc0575ae418e4f489ce3245f8b741a821e4"

      def install
        bin.install "red-cli"
      end
    end
  end

  test do
    system "#{bin}/red-cli -v"
  end
end
