# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Red < Formula
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.0.3"

  on_macos do
    url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.3/red_0.0.3_Darwin_all.tar.gz"
    sha256 "52580599cd586785afed18da7976a439aeaa2596a85f5b8b5b7cb9bcf5188857"

    def install
      bin.install "red"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.3/red_0.0.3_Linux_x86_64.tar.gz"
      sha256 "f84cf00550ce5b22033a2386320164d57b0f1c22700840433a1b73100e393bf6"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.3/red_0.0.3_Linux_armv6.tar.gz"
      sha256 "b785a87395cea343bf9ce0336c5f725c8afbd54afa4078560d9d79b8ada83a57"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.3/red_0.0.3_Linux_arm64.tar.gz"
      sha256 "06e3d24a149e3be29fa3d5ccec9c4f0f207dc8327ec78a2991c3242dd43098ab"

      def install
        bin.install "red"
      end
    end
  end

  test do
    system "#{bin}/red -v"
  end
end
