# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Red < Formula
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.0.4"

  on_macos do
    url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.4/red_0.0.4_Darwin_all.tar.gz"
    sha256 "3c44d2309ac0faf18d8c55a6efe8e999659e2eab9519ab0e02602887f4b05347"

    def install
      bin.install "red"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.4/red_0.0.4_Linux_x86_64.tar.gz"
      sha256 "09d7d14050eebe4afe6b8a214af700fe86a85a5a1f158afb5d55e194e9e18737"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.4/red_0.0.4_Linux_armv6.tar.gz"
      sha256 "0d012c0c3403d0fc60c0fef8255fcba39cc9de7d29220d04466a81493713d96c"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.4/red_0.0.4_Linux_arm64.tar.gz"
      sha256 "73ad14b29f047f967ce334d8f9eed18a37c64d2401a8cf00d81d989793cf5a41"

      def install
        bin.install "red"
      end
    end
  end

  test do
    system "#{bin}/red -v"
  end
end
