# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Red < Formula
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.0.5"

  on_macos do
    url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.5/red_0.0.5_Darwin_all.tar.gz"
    sha256 "086700d7a63fac2ac5fb1c6722adc82ebf2eb71893edb4aa0be041d281f80c12"

    def install
      bin.install "red"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.5/red_0.0.5_Linux_arm64.tar.gz"
      sha256 "87abad79e6324323bf9869126ef02689ee9ab4f9f158dddfc54c74408002e661"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.5/red_0.0.5_Linux_x86_64.tar.gz"
      sha256 "7c3f989c14027d8e81a7639751a139e7b7f107bf546b4169b8a113e5e4a0097d"

      def install
        bin.install "red"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.0.5/red_0.0.5_Linux_armv6.tar.gz"
      sha256 "2fecb703d8e0a82e658251acc36d2a5bdbf0ae17b71eedfafd01cd0a951c8828"

      def install
        bin.install "red"
      end
    end
  end

  test do
    system "#{bin}/red -v"
  end
end
