# This file was generated by GoReleaser. DO NOT EDIT.
cask "red-cli" do
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.1.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "red-cli"

  on_macos do
    on_intel do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.8/red-cli_0.1.8_darwin_amd64.tar.gz"
      sha256 "989981ca26b1038ff08e80ee96d200d6e8bcf3424e3002dc7358daa138a875c7"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.8/red-cli_0.1.8_darwin_arm64.tar.gz"
      sha256 "e4334539a97e2f52a9500a9f50af9c583ff73f76cd4f5eb0c5e930684840e708"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.8/red-cli_0.1.8_linux_amd64.tar.gz"
      sha256 "8045cbed4130868225565463a14706aca80fa735b9ae0872fb24598f91e8c445"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.8/red-cli_0.1.8_linux_arm64.tar.gz"
      sha256 "52bc7741418e69dea33d90d933a49fe21ab0536ef1e645ee7535ba45ac8b2392"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'red-cli' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/red-cli"]
    end
  end

  # No zap stanza required
end
