# This file was generated by GoReleaser. DO NOT EDIT.
cask "red-cli" do
  desc "Redmine CLI"
  homepage "https://github.com/mrjefflarry/redmine-cli"
  version "0.1.10"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "red-cli"

  on_macos do
    on_intel do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.10/red-cli_0.1.10_darwin_amd64.tar.gz"
      sha256 "a9784dde19be4a4d42bd2b28003659cd1ec2f3b7565967ee0f39d4680126fea8"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.10/red-cli_0.1.10_darwin_arm64.tar.gz"
      sha256 "6d4dd39598c60dba82a743318421ede49380c1d2d6dad3c0d9bfd65c22133e56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.10/red-cli_0.1.10_linux_amd64.tar.gz"
      sha256 "9d8b7650e69b7ee328f274c1276d6147e12fc7347d2ac4000771ac41d3f9c3d4"
    end
    on_arm do
      url "https://github.com/MrJeffLarry/redmine-cli/releases/download/v0.1.10/red-cli_0.1.10_linux_arm64.tar.gz"
      sha256 "3e74d59dc6b4e3d8e3f461fc15d857f4194f1aa41a911d15cab4183538143bc6"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      # replace 'red-cli' with the actual binary name
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/red-cli"]
    end
  end

  # No zap stanza required
end
